### ISSUE TITLE
Reminder if players can vote

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/EssenceGlue#2]
- Player should be able to turn it off via /config (but default on)
- Lists all available votes on login (if any exist)
- Lists all available votes every 15 minutes (if any exist), just have a runnable on 15 min timer

**Comment by Diet-Cola** [comment]
@wingzero54 Do you want this to automatically output every 15 mins? seems very spammy imo

**Comment by Protonull** [comment]
Just a friendly reminder that you're now able to vote :)
Just a friendly reminder that you're now able to vote :)
Just a friendly reminder that you're now able to vote :)
Just a friendly reminder that you're now able to vote :)
Just a friendly reminder that you're now able to vote :)
Just a friendly reminder that you're now able to vote :)
Just a friendly reminder that you're now able to vote :)
Just a friendly reminder that you're now able to vote :)
Just a friendly reminder that you're now able to vote :)
Just a friendly reminder that you're now able to vote :)
Just a friendly reminder that you're now able to vote :)
Just a friendly reminder that you're now able to vote :)
Just a friendly reminder that you're now able to vote :)
Just a friendly reminder that you're now able to vote :)
Just a friendly reminder that you're now able to vote :)
Just a friendly reminder that you're now able to vote :)
Just a friendly reminder that you're now able to vote :)
Just a friendly reminder that you're now able to vote :)
Just a friendly reminder that you're now able to vote :)

**Comment by wingzero54** [comment]
> 
> 
> @wingzero54 Do you want this to automatically output every 15 mins? seems very spammy imo

Let's do every 30 minutes
