### ISSUE TITLE
Some players do not get daily essence

### ISSUE THREAD

**Issue by wingzero54** [CivClassic/EssenceGlue#5]
Reported by a few different players, consistent over the course of several days. Some players are getting their daily essence, some are not. Some pearled players report that their streak timer gets stuck at 30 minutes, and some regular players report the same. It may be related to the bad TPS? Failure to get their streak coincides with periods of bad TPS

**Comment by Maxopoly** [comment]
Need names and time of incidents to investigate

**Comment by wingzero54** [comment]
Virizion and Seldomshock did not get their daily essence on 11/19, but they did on 11/20. So my assumption is the bad tps broke a timer or something

**Comment by wingzero54** [comment]
Very likely related to [this other issue](https://github.com/CivClassic/BanStick/issues/18)

**Comment by Inframission** [comment]
For the last few days I've gotten essence but only after staying afk for an hour or two. 
I recommend checking to see if bots have streaks lower than 8 to test whether longer playtime consistently rewards essence

**Comment by Ameliorate** [comment]
\>I recommend checking to see if bots have streaks lower than 8 to test whether longer playtime consistently rewards essence

Many people disable essence claiming on their bots, however.

**Comment by Inframission** [comment]
I feel confident this issue hasn't presented in a few months. If there aren't more recent concerns I suggest closing this.

**Comment by wingzero54** [comment]
I feel confident that if we raise pearl costs people would suddenly start saying this is an issue again like they did last time
